# 主要輸入資料
data:
  transaction: !!str data/input/transaction.csv
  target: !!str data/input/target.csv

# 主要輸入資料中使用的欄位
column:
  transaction:
    land_id: !!str land_id
    coordinate: !!str tran_coordinate
    value: !!str 單價元平方公尺
    date: !!str date
  target:
    id: !!str id 
    coordinate: !!str coordinate

# 輸出資料夾
output_folder:
  main: !!str data/train_data/basic
  proc: !!str data/train_data/basic/procces

# 方法參數
method:
  1_distance_threshold: !!int 500 # meter
  1_group_method: !!str DBSCAN
  2_reference_point_module: !!str PropGman.method.reference_point
  2_reference_point_func: !!str UDLR # 上下左右
  2_reference_point_distance: !!int 3000 # 公尺，詳細測試: EDA_and_preprocess\code\supplementary\m0__effective_range_select.py
  2_lat_degree_per_100_meter: !!float 0.0009027527123486883 # 詳細測試: EDA_and_preprocess\code\method_procces\1_reference_point.py
  2_long_degree_per_100_meter: !!float 0.0009902726875066093 # 詳細測試: EDA_and_preprocess\code\method_procces\1_reference_point.py

# 流程控制
control:
  overwrite_record: !!bool false # 是否要覆蓋已有的輸出資料
  output_proc_file: !!bool true # 是否要輸出過程中產生的資料，可用來恢復進度

# GMAN 所需的 spatial embedding (這部分使用 node2vec，edge 值使用直線距離)
SE:

# ----------------------------------- 動態 -----------------------------------
# 紀錄執行進度
procces_record:
  step1: !!bool false # group land use DBSCAN
  step2: !!bool false # Get reference point
  step3: !!bool false # Calculate distance matrix
  step4: !!bool false # Calculate customized index
  step5: !!bool false # Create training data 
  step6: !!bool false # Generate SE data