data:
  transaction: !!str data/basic/transaction.csv
  target: !!str data/basic/target.csv
column:
  transaction:
    land_id: !!str land_id
    coordinate: !!str tran_coordinate
    value: !!str 單價元平方公尺
    date: !!str date
  target:
    id: !!str id # 測試
    coordinate: !!str coordinate
output_folder:
  main: !!str data/train_data/
  proc: !!str data/train_data/procces
method:
  distance_threshold: !!int 500 # meter
SE: